// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlwgpmfrbeafceibpeua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsd2dwbWZyYmVhZmNlaWJwZXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzk2NDEsImV4cCI6MjA1Mzg1NTY0MX0.cczbgUl24dubsf2qxJqLJs-dw1Et90_O7MsAcSfqRpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);